/* tslint:disable */
/* eslint-disable */
/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CodeObject } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AllergyApi - axios parameter creator
 * @export
 */
export const AllergyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * \'The allergy endpoint returns information about the UKG Pro allergy configurations.\' 
         * @summary Retrieve all allergy configurations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configurationsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/allergy`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OauthSecurity required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OauthSecurity", ["recruiting.domain.third-party-job-board-integrations.auto-feed"], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/allergy',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * \'Creates a new UKG Pro allergy configuration.\' 
         * @summary Create a new allergy configuration
         * @param {CodeObject} codeObject The allergy code to be written.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createConfiguration: async (codeObject: CodeObject, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'codeObject' is not null or undefined
            assertParamExists('createConfiguration', 'codeObject', codeObject)
            const localVarPath = `/allergy`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OauthSecurity required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OauthSecurity", ["recruiting.domain.third-party-job-board-integrations.auto-feed"], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: codeObject,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/allergy',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(codeObject, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * \'Allows the ability update a single allergy configuration.\' 
         * @summary Update a single allergy configuration
         * @param {string} code Project code.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSingleConfiguration: async (code: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('updateSingleConfiguration', 'code', code)
            const localVarPath = `/allergy/{code}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code !== undefined ? code : `-code-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OauthSecurity required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OauthSecurity", ["recruiting.domain.third-party-job-board-integrations.auto-feed"], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/allergy/{code}',
                httpMethod: 'PUT'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AllergyApi - functional programming interface
 * @export
 */
export const AllergyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AllergyApiAxiosParamCreator(configuration)
    return {
        /**
         * \'The allergy endpoint returns information about the UKG Pro allergy configurations.\' 
         * @summary Retrieve all allergy configurations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async configurationsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CodeObject>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.configurationsGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * \'Creates a new UKG Pro allergy configuration.\' 
         * @summary Create a new allergy configuration
         * @param {AllergyApiCreateConfigurationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createConfiguration(requestParameters: AllergyApiCreateConfigurationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const codeObject: CodeObject = {
                description: requestParameters.description,
                code: requestParameters.code
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.createConfiguration(codeObject, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * \'Allows the ability update a single allergy configuration.\' 
         * @summary Update a single allergy configuration
         * @param {AllergyApiUpdateSingleConfigurationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateSingleConfiguration(requestParameters: AllergyApiUpdateSingleConfigurationRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateSingleConfiguration(requestParameters.code, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AllergyApi - factory interface
 * @export
 */
export const AllergyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AllergyApiFp(configuration)
    return {
        /**
         * \'The allergy endpoint returns information about the UKG Pro allergy configurations.\' 
         * @summary Retrieve all allergy configurations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        configurationsGet(options?: AxiosRequestConfig): AxiosPromise<Array<CodeObject>> {
            return localVarFp.configurationsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * \'Creates a new UKG Pro allergy configuration.\' 
         * @summary Create a new allergy configuration
         * @param {AllergyApiCreateConfigurationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createConfiguration(requestParameters: AllergyApiCreateConfigurationRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createConfiguration(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * \'Allows the ability update a single allergy configuration.\' 
         * @summary Update a single allergy configuration
         * @param {AllergyApiUpdateSingleConfigurationRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateSingleConfiguration(requestParameters: AllergyApiUpdateSingleConfigurationRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateSingleConfiguration(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createConfiguration operation in AllergyApi.
 * @export
 * @interface AllergyApiCreateConfigurationRequest
 */
export type AllergyApiCreateConfigurationRequest = {
    
} & CodeObject

/**
 * Request parameters for updateSingleConfiguration operation in AllergyApi.
 * @export
 * @interface AllergyApiUpdateSingleConfigurationRequest
 */
export type AllergyApiUpdateSingleConfigurationRequest = {
    
    /**
    * Project code.
    * @type {string}
    * @memberof AllergyApiUpdateSingleConfiguration
    */
    readonly code: string
    
}

/**
 * AllergyApiGenerated - object-oriented interface
 * @export
 * @class AllergyApiGenerated
 * @extends {BaseAPI}
 */
export class AllergyApiGenerated extends BaseAPI {
    /**
     * \'The allergy endpoint returns information about the UKG Pro allergy configurations.\' 
     * @summary Retrieve all allergy configurations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AllergyApiGenerated
     */
    public configurationsGet(options?: AxiosRequestConfig) {
        return AllergyApiFp(this.configuration).configurationsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * \'Creates a new UKG Pro allergy configuration.\' 
     * @summary Create a new allergy configuration
     * @param {AllergyApiCreateConfigurationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AllergyApiGenerated
     */
    public createConfiguration(requestParameters: AllergyApiCreateConfigurationRequest, options?: AxiosRequestConfig) {
        return AllergyApiFp(this.configuration).createConfiguration(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * \'Allows the ability update a single allergy configuration.\' 
     * @summary Update a single allergy configuration
     * @param {AllergyApiUpdateSingleConfigurationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AllergyApiGenerated
     */
    public updateSingleConfiguration(requestParameters: AllergyApiUpdateSingleConfigurationRequest, options?: AxiosRequestConfig) {
        return AllergyApiFp(this.configuration).updateSingleConfiguration(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
