/* tslint:disable */
/* eslint-disable */
/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { EmployeeSecurityUserDetails } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * EmployeeSecurityUserDetailsApi - axios parameter creator
 * @export
 */
export const EmployeeSecurityUserDetailsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \"View\" role for the \"Personnel Integration\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).
         * @summary Get employee security user details
         * @param {string} [userName] 
         * @param {string} [employeeID] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetails: async (userName?: string, employeeID?: string, page?: number, perPage?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/personnel/v1/employee-security-user-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OauthSecurity required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OauthSecurity", ["recruiting.domain.third-party-job-board-integrations.auto-feed"], configuration)
            if (userName !== undefined) {
                localVarQueryParameter['userName'] = userName;
            }

            if (employeeID !== undefined) {
                localVarQueryParameter['employeeID'] = employeeID;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_Page'] = perPage;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/personnel/v1/employee-security-user-details',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeSecurityUserDetailsApi - functional programming interface
 * @export
 */
export const EmployeeSecurityUserDetailsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeeSecurityUserDetailsApiAxiosParamCreator(configuration)
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \"View\" role for the \"Personnel Integration\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).
         * @summary Get employee security user details
         * @param {EmployeeSecurityUserDetailsApiGetDetailsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDetails(requestParameters: EmployeeSecurityUserDetailsApiGetDetailsRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EmployeeSecurityUserDetails>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDetails(requestParameters.userName, requestParameters.employeeID, requestParameters.page, requestParameters.perPage, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EmployeeSecurityUserDetailsApi - factory interface
 * @export
 */
export const EmployeeSecurityUserDetailsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeeSecurityUserDetailsApiFp(configuration)
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \"View\" role for the \"Personnel Integration\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).
         * @summary Get employee security user details
         * @param {EmployeeSecurityUserDetailsApiGetDetailsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDetails(requestParameters: EmployeeSecurityUserDetailsApiGetDetailsRequest = {}, options?: AxiosRequestConfig): AxiosPromise<Array<EmployeeSecurityUserDetails>> {
            return localVarFp.getDetails(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getDetails operation in EmployeeSecurityUserDetailsApi.
 * @export
 * @interface EmployeeSecurityUserDetailsApiGetDetailsRequest
 */
export type EmployeeSecurityUserDetailsApiGetDetailsRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof EmployeeSecurityUserDetailsApiGetDetails
    */
    readonly userName?: string
    
    /**
    * 
    * @type {string}
    * @memberof EmployeeSecurityUserDetailsApiGetDetails
    */
    readonly employeeID?: string
    
    /**
    * 
    * @type {number}
    * @memberof EmployeeSecurityUserDetailsApiGetDetails
    */
    readonly page?: number
    
    /**
    * 
    * @type {number}
    * @memberof EmployeeSecurityUserDetailsApiGetDetails
    */
    readonly perPage?: number
    
}

/**
 * EmployeeSecurityUserDetailsApiGenerated - object-oriented interface
 * @export
 * @class EmployeeSecurityUserDetailsApiGenerated
 * @extends {BaseAPI}
 */
export class EmployeeSecurityUserDetailsApiGenerated extends BaseAPI {
    /**
     * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \"View\" role for the \"Personnel Integration\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).
     * @summary Get employee security user details
     * @param {EmployeeSecurityUserDetailsApiGetDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeSecurityUserDetailsApiGenerated
     */
    public getDetails(requestParameters: EmployeeSecurityUserDetailsApiGetDetailsRequest = {}, options?: AxiosRequestConfig) {
        return EmployeeSecurityUserDetailsApiFp(this.configuration).getDetails(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
