/* tslint:disable */
/* eslint-disable */
/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { PayRegister } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * PayRegisterApi - axios parameter creator
 * @export
 */
export const PayRegisterApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \"View\" role for the \"Payroll Integration\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}). 
         * @summary Get Pay Register
         * @param {string} [employeeId] 
         * @param {string} [companyId] 
         * @param {string} [checkId] 
         * @param {string} [employeeNumber] 
         * @param {string} [documentNumber] 
         * @param {string} [payGroup] 
         * @param {string} [periodControl] 
         * @param {string} [payDate] 
         * @param {string} [periodEndDate] 
         * @param {string} [periodStartDate] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (employeeId?: string, companyId?: string, checkId?: string, employeeNumber?: string, documentNumber?: string, payGroup?: string, periodControl?: string, payDate?: string, periodEndDate?: string, periodStartDate?: string, page?: number, perPage?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payroll/v1/pay-register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OauthSecurity required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OauthSecurity", ["recruiting.domain.third-party-job-board-integrations.auto-feed"], configuration)
            if (employeeId !== undefined) {
                localVarQueryParameter['employeeId'] = employeeId;
            }

            if (companyId !== undefined) {
                localVarQueryParameter['companyId'] = companyId;
            }

            if (checkId !== undefined) {
                localVarQueryParameter['checkId'] = checkId;
            }

            if (employeeNumber !== undefined) {
                localVarQueryParameter['employeeNumber'] = employeeNumber;
            }

            if (documentNumber !== undefined) {
                localVarQueryParameter['documentNumber'] = documentNumber;
            }

            if (payGroup !== undefined) {
                localVarQueryParameter['payGroup'] = payGroup;
            }

            if (periodControl !== undefined) {
                localVarQueryParameter['periodControl'] = periodControl;
            }

            if (payDate !== undefined) {
                localVarQueryParameter['payDate'] = (payDate as any instanceof Date) ?
                    (payDate as any).toISOString() :
                    payDate;
            }

            if (periodEndDate !== undefined) {
                localVarQueryParameter['periodEndDate'] = periodEndDate;
            }

            if (periodStartDate !== undefined) {
                localVarQueryParameter['periodStartDate'] = periodStartDate;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_Page'] = perPage;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/payroll/v1/pay-register',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PayRegisterApi - functional programming interface
 * @export
 */
export const PayRegisterApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PayRegisterApiAxiosParamCreator(configuration)
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \"View\" role for the \"Payroll Integration\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}). 
         * @summary Get Pay Register
         * @param {PayRegisterApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(requestParameters: PayRegisterApiGetRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PayRegister>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(requestParameters.employeeId, requestParameters.companyId, requestParameters.checkId, requestParameters.employeeNumber, requestParameters.documentNumber, requestParameters.payGroup, requestParameters.periodControl, requestParameters.payDate, requestParameters.periodEndDate, requestParameters.periodStartDate, requestParameters.page, requestParameters.perPage, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PayRegisterApi - factory interface
 * @export
 */
export const PayRegisterApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PayRegisterApiFp(configuration)
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \"View\" role for the \"Payroll Integration\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}). 
         * @summary Get Pay Register
         * @param {PayRegisterApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(requestParameters: PayRegisterApiGetRequest = {}, options?: AxiosRequestConfig): AxiosPromise<Array<PayRegister>> {
            return localVarFp.get(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for get operation in PayRegisterApi.
 * @export
 * @interface PayRegisterApiGetRequest
 */
export type PayRegisterApiGetRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly employeeId?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly companyId?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly checkId?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly employeeNumber?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly documentNumber?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly payGroup?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly periodControl?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly payDate?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly periodEndDate?: string
    
    /**
    * 
    * @type {string}
    * @memberof PayRegisterApiGet
    */
    readonly periodStartDate?: string
    
    /**
    * 
    * @type {number}
    * @memberof PayRegisterApiGet
    */
    readonly page?: number
    
    /**
    * 
    * @type {number}
    * @memberof PayRegisterApiGet
    */
    readonly perPage?: number
    
}

/**
 * PayRegisterApiGenerated - object-oriented interface
 * @export
 * @class PayRegisterApiGenerated
 * @extends {BaseAPI}
 */
export class PayRegisterApiGenerated extends BaseAPI {
    /**
     * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \"View\" role for the \"Payroll Integration\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}). 
     * @summary Get Pay Register
     * @param {PayRegisterApiGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PayRegisterApiGenerated
     */
    public get(requestParameters: PayRegisterApiGetRequest = {}, options?: AxiosRequestConfig) {
        return PayRegisterApiFp(this.configuration).get(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
