/* tslint:disable */
/* eslint-disable */
/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { UserProfileDetails } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * UserProfileDetailsApi - axios parameter creator
 * @export
 */
export const UserProfileDetailsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \\\"View\\\" role for the \\\"Personnel Integration\\\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).
         * @summary Get all user profile details
         * @param {string} [masterCompany] 
         * @param {string} [userStatus] 
         * @param {string} [userId] 
         * @param {string} [roleId] 
         * @param {string} [companyId] 
         * @param {string} [employeeId] 
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDetails: async (masterCompany?: string, userStatus?: string, userId?: string, roleId?: string, companyId?: string, employeeId?: string, page?: number, perPage?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/personnel/v1/user-profile-details`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OauthSecurity required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OauthSecurity", ["recruiting.domain.third-party-job-board-integrations.auto-feed"], configuration)
            if (masterCompany !== undefined) {
                localVarQueryParameter['masterCompany'] = masterCompany;
            }

            if (userStatus !== undefined) {
                localVarQueryParameter['userStatus'] = userStatus;
            }

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }

            if (roleId !== undefined) {
                localVarQueryParameter['roleId'] = roleId;
            }

            if (companyId !== undefined) {
                localVarQueryParameter['companyId'] = companyId;
            }

            if (employeeId !== undefined) {
                localVarQueryParameter['employeeId'] = employeeId;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_Page'] = perPage;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/personnel/v1/user-profile-details',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserProfileDetailsApi - functional programming interface
 * @export
 */
export const UserProfileDetailsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserProfileDetailsApiAxiosParamCreator(configuration)
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \\\"View\\\" role for the \\\"Personnel Integration\\\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).
         * @summary Get all user profile details
         * @param {UserProfileDetailsApiGetAllDetailsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllDetails(requestParameters: UserProfileDetailsApiGetAllDetailsRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserProfileDetails>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllDetails(requestParameters.masterCompany, requestParameters.userStatus, requestParameters.userId, requestParameters.roleId, requestParameters.companyId, requestParameters.employeeId, requestParameters.page, requestParameters.perPage, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserProfileDetailsApi - factory interface
 * @export
 */
export const UserProfileDetailsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserProfileDetailsApiFp(configuration)
    return {
        /**
         * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \\\"View\\\" role for the \\\"Personnel Integration\\\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).
         * @summary Get all user profile details
         * @param {UserProfileDetailsApiGetAllDetailsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllDetails(requestParameters: UserProfileDetailsApiGetAllDetailsRequest = {}, options?: AxiosRequestConfig): AxiosPromise<Array<UserProfileDetails>> {
            return localVarFp.getAllDetails(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllDetails operation in UserProfileDetailsApi.
 * @export
 * @interface UserProfileDetailsApiGetAllDetailsRequest
 */
export type UserProfileDetailsApiGetAllDetailsRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof UserProfileDetailsApiGetAllDetails
    */
    readonly masterCompany?: string
    
    /**
    * 
    * @type {string}
    * @memberof UserProfileDetailsApiGetAllDetails
    */
    readonly userStatus?: string
    
    /**
    * 
    * @type {string}
    * @memberof UserProfileDetailsApiGetAllDetails
    */
    readonly userId?: string
    
    /**
    * 
    * @type {string}
    * @memberof UserProfileDetailsApiGetAllDetails
    */
    readonly roleId?: string
    
    /**
    * 
    * @type {string}
    * @memberof UserProfileDetailsApiGetAllDetails
    */
    readonly companyId?: string
    
    /**
    * 
    * @type {string}
    * @memberof UserProfileDetailsApiGetAllDetails
    */
    readonly employeeId?: string
    
    /**
    * 
    * @type {number}
    * @memberof UserProfileDetailsApiGetAllDetails
    */
    readonly page?: number
    
    /**
    * 
    * @type {number}
    * @memberof UserProfileDetailsApiGetAllDetails
    */
    readonly perPage?: number
    
}

/**
 * UserProfileDetailsApiGenerated - object-oriented interface
 * @export
 * @class UserProfileDetailsApiGenerated
 * @extends {BaseAPI}
 */
export class UserProfileDetailsApiGenerated extends BaseAPI {
    /**
     * If no pagination parameters specified, the default/max is applied. Permissions - UKG Pro service account must have \\\"View\\\" role for the \\\"Personnel Integration\\\" Web Service. Headers - US-Customer-Api-Key, Authorization (base64 encoded {username}:{password}).
     * @summary Get all user profile details
     * @param {UserProfileDetailsApiGetAllDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserProfileDetailsApiGenerated
     */
    public getAllDetails(requestParameters: UserProfileDetailsApiGetAllDetailsRequest = {}, options?: AxiosRequestConfig) {
        return UserProfileDetailsApiFp(this.configuration).getAllDetails(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
