/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicationOpportunity
 */
export interface ApplicationOpportunity {
    /**
     * The id of the opportunity that the candidate has applied for.
     * @type {string}
     * @memberof ApplicationOpportunity
     */
    'id'?: string;
}

