/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ApplicationHireDetailsCompany
 */
export interface ApplicationHireDetailsCompany {
    /**
     * The id of the legal entity associated with the specified application. If not specified, it will be defaulted to the legal entity associated with the opportunity for the application.
     * @type {string}
     * @memberof ApplicationHireDetailsCompany
     */
    'id'?: string;
    /**
     * The legal entity name
     * @type {string}
     * @memberof ApplicationHireDetailsCompany
     */
    'name'?: string;
    /**
     * The legal entity code
     * @type {string}
     * @memberof ApplicationHireDetailsCompany
     */
    'code'?: string;
    /**
     * The legal entity’s Doing Business As name
     * @type {string}
     * @memberof ApplicationHireDetailsCompany
     */
    'doing_business_as'?: string;
}

