/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AuditDetails
 */
export interface AuditDetails {
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audDateTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audKey1Label'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audKey2Label'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audKey3Label'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audKey1Value'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audKey2Value'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audKey3Value'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audTableName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audFieldName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audOldValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audNewValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audAction'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuditDetails
     */
    'audSystemID'?: string;
}

