/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Screening } from './screening';

/**
 * An array of background check packages; at most 100.
 * @export
 * @interface BackgroundChecksPackages
 */
export interface BackgroundChecksPackages {
    /**
     * The id of the package.
     * @type {string}
     * @memberof BackgroundChecksPackages
     */
    'id': string;
    /**
     * The name of the package. Maximum of 100 characters.
     * @type {string}
     * @memberof BackgroundChecksPackages
     */
    'name': string;
    /**
     * An array of background check screenings; at most 100.
     * @type {Array<Screening>}
     * @memberof BackgroundChecksPackages
     */
    'screenings'?: Array<Screening>;
}

