/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BusinessRuleImportMessage
 */
export interface BusinessRuleImportMessage {
    /**
     * 
     * @type {string}
     * @memberof BusinessRuleImportMessage
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BusinessRuleImportMessage
     */
    'severity'?: BusinessRuleImportMessageSeverityEnum;
}

type BusinessRuleImportMessageSeverityEnum = 0 | 1 | 2 | 3


