/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CandidatePreferredLocale
 */
export interface CandidatePreferredLocale {
    /**
     * The id of the candidate’s preferred language.
     * @type {string}
     * @memberof CandidatePreferredLocale
     */
    'id'?: string;
    /**
     * The preferred language code: en-US,  en-GB,  fr-CA,  es-ES,  pt-BR,  de-DE,  zh-CN 
     * @type {string}
     * @memberof CandidatePreferredLocale
     */
    'code'?: string;
}

