/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CountryQuestionResponsesQuestion } from './country-question-responses-question';

/**
 * 
 * @export
 * @interface CountryQuestionResponses
 */
export interface CountryQuestionResponses {
    /**
     * 
     * @type {CountryQuestionResponsesQuestion}
     * @memberof CountryQuestionResponses
     */
    'question'?: CountryQuestionResponsesQuestion;
    /**
     * 
     * @type {any}
     * @memberof CountryQuestionResponses
     */
    'response'?: any;
}

