/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreatorBackgroundCheckIntegration
 */
export interface CreatorBackgroundCheckIntegration {
    /**
     * The internal Recruiting id of the third party background check vendor associated with the request.
     * @type {string}
     * @memberof CreatorBackgroundCheckIntegration
     */
    'id'?: string;
}

