/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ContactInfo } from './contact-info';
import { CreatorBackgroundCheckIntegration } from './creator-background-check-integration';
import { CreatorPreferredLocale } from './creator-preferred-locale';
import { Hyperlinks } from './hyperlinks';
import { Links } from './links';
import { Name } from './name';

/**
 * The section that contains details of a recruiter who submitted this background check order.
 * @export
 * @interface Creator
 */
export interface Creator {
    /**
     * The id of the recruiter who created the background check order.
     * @type {string}
     * @memberof Creator
     */
    'id'?: string;
    /**
     * The recruiter id in the core HR system.
     * @type {string}
     * @memberof Creator
     */
    'person_id'?: string;
    /**
     * The date of this user creation date.
     * @type {string}
     * @memberof Creator
     */
    'created_at'?: string;
    /**
     * The alternative user id that can be used in third-party vendors’ integrations. Returned only for users with the “recruiter”, “hiring-manager”, or “recruiting-administrator” role.
     * @type {string}
     * @memberof Creator
     */
    'integration_user_id'?: string;
    /**
     * A flag indicating whether the recruiter is an internal employee. 
     * @type {boolean}
     * @memberof Creator
     */
    'is_internal'?: boolean;
    /**
     * A flag indicating whether the recruiter is an active employee. Can only be specified when is_internal is true.
     * @type {boolean}
     * @memberof Creator
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {CreatorPreferredLocale}
     * @memberof Creator
     */
    'preferred_locale'?: CreatorPreferredLocale;
    /**
     * 
     * @type {Array<Name>}
     * @memberof Creator
     */
    'name'?: Array<Name>;
    /**
     * 
     * @type {Array<ContactInfo>}
     * @memberof Creator
     */
    'contact_info'?: Array<ContactInfo>;
    /**
     * 
     * @type {Array<any>}
     * @memberof Creator
     */
    'roles'?: Array<any>;
    /**
     * 
     * @type {Array<Hyperlinks>}
     * @memberof Creator
     */
    'hyperlinks'?: Array<Hyperlinks>;
    /**
     * 
     * @type {string}
     * @memberof Creator
     */
    'updated_at'?: string;
    /**
     * 
     * @type {Array<Links>}
     * @memberof Creator
     */
    'links'?: Array<Links>;
    /**
     * 
     * @type {CreatorBackgroundCheckIntegration}
     * @memberof Creator
     */
    'background_check_integration'?: CreatorBackgroundCheckIntegration;
}

