/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmpDedHistoryEffectiveChangeDate
 */
export interface EmpDedHistoryEffectiveChangeDate {
    /**
     * 
     * @type {string}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'employeeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'deductionCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'effectiveDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'fieldValueDataType'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'fieldValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'fieldValueDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'fieldValueNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmpDedHistoryEffectiveChangeDate
     */
    'changeReason'?: string;
}

