/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmpCompensationDetails
 */
export interface EmpCompensationDetails {
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'employeeID'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'companyID'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'annualSalary'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'hourlyPayRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'weeklyPayRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'payPeriodPayRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'currencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'otherRate1'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'otherRate2'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'otherRate3'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'otherRate4'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'payGroupDescription'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'piecePayRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'primaryJobCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'jobSalaryGrade'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'jobChangeReasonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'jobGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'jobTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'dateInJob'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'dateLastPaid'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'dateLastWorked'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'dateOfLastSalaryReview'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'dateOfNextSalayrReview'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmpCompensationDetails
     */
    'isAutoAllocated'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmpCompensationDetails
     */
    'isAutoPaid'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmpCompensationDetails
     */
    'isSeasonalWorker'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmpCompensationDetails
     */
    'isHighlyCompensated'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmpCompensationDetails
     */
    'isMultipleJob'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'payGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'payPeriod'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'payScaleCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'salaryOrHourlyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'fullTimeOrPartTimeCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'scheduledFullTimeEquivalency'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'scheduledPeriodWorkHours'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'scheduledAnnualWorkHours'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'weeklyHours'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'primaryShiftCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'primaryShiftGroupCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'avgPayRateCurPer'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'bonusTotalHrs'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'bonusTotalOtHrs'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'datePaidThru'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'emplStatus'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'totalAnnSalary'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'distributionCenterCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmpCompensationDetails
     */
    'numberOfPayments'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'performanceReviewRating'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmpCompensationDetails
     */
    'performanceReviewType'?: string;
}

