/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeEducationModel
 */
export interface EmployeeEducationModel {
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'employeeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'systemId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'school'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'educationLevel'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'educationMajor'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'educationMinor'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'gpa'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'beginDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'endDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeEducationModel
     */
    'isGraduate'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeEducationModel
     */
    'isHighestLevel'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'employeeNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeEducationModel
     */
    'country'?: string;
}

