/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeStatus
 */
export interface EmployeeStatus {
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'asOfDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'employeeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'companyId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeStatus
     */
    'triggerTermination'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'statusStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'statusReason'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'statusReasonDesc'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeStatus
     */
    'isPrimary'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'isPrimaryEffectiveDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeStatus
     */
    'originalHireDate'?: string;
}

