/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeePayStatementTaxesModel
 */
export interface EmployeePayStatementTaxesModel {
    /**
     * 
     * @type {number}
     * @memberof EmployeePayStatementTaxesModel
     */
    'amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeePayStatementTaxesModel
     */
    'amountytd'?: number;
    /**
     * 
     * @type {number}
     * @memberof EmployeePayStatementTaxesModel
     */
    'basisamount'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeePayStatementTaxesModel
     */
    'taxdescription'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeePayStatementTaxesModel
     */
    'taxcode'?: string;
}

