/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeDeductionBenefitOptionChangeDate
 */
export interface EmployeeDeductionBenefitOptionChangeDate {
    /**
     * 
     * @type {string}
     * @memberof EmployeeDeductionBenefitOptionChangeDate
     */
    'companyID'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDeductionBenefitOptionChangeDate
     */
    'deductionCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDeductionBenefitOptionChangeDate
     */
    'employeeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeDeductionBenefitOptionChangeDate
     */
    'optionDate'?: string;
}

