/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeIdsResponseMultistatusInner } from './employee-ids-response-multistatus-inner';

/**
 * 
 * @export
 * @interface EmployeeIdsResponse
 */
export interface EmployeeIdsResponse {
    /**
     * 
     * @type {string}
     * @memberof EmployeeIdsResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeIdsResponse
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeIdsResponse
     */
    'detail'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeeIdsResponse
     */
    'errorCount'?: number;
    /**
     * 
     * @type {Array<EmployeeIdsResponseMultistatusInner>}
     * @memberof EmployeeIdsResponse
     */
    'multistatus'?: Array<EmployeeIdsResponseMultistatusInner>;
}

