/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeJobDto
 */
export interface EmployeeJobDto {
    /**
     * 
     * @type {number}
     * @memberof EmployeeJobDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof EmployeeJobDto
     */
    'jobName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeJobDto
     */
    'jobDesc'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeJobDto
     */
    'jobStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof EmployeeJobDto
     */
    'jobEndDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EmployeeJobDto
     */
    'jobPreferred'?: boolean;
}

