/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PtoPlans } from './pto-plans';

/**
 * Only present if status is success
 * @export
 * @interface MultiStatusResponseMultistatusInnerBody
 */
export interface MultiStatusResponseMultistatusInnerBody {
    /**
     * 
     * @type {string}
     * @memberof MultiStatusResponseMultistatusInnerBody
     */
    'eeid'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof MultiStatusResponseMultistatusInnerBody
     */
    'coid'?: Array<string>;
    /**
     * 
     * @type {PtoPlans}
     * @memberof MultiStatusResponseMultistatusInnerBody
     */
    'schema'?: PtoPlans;
}

