/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MultiStatusDtoObject
 */
export interface MultiStatusDtoObject {
    /**
     * 
     * @type {string}
     * @memberof MultiStatusDtoObject
     */
    'id'?: string;
    /**
     * 
     * @type {number}
     * @memberof MultiStatusDtoObject
     */
    'sequenceId'?: number;
    /**
     * 
     * @type {string}
     * @memberof MultiStatusDtoObject
     */
    'status'?: string;
    /**
     * 
     * @type {object}
     * @memberof MultiStatusDtoObject
     */
    'modelState'?: object;
}

