/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The candidate’s prefix.
 * @export
 * @interface NamePrefix
 */
export interface NamePrefix {
    /**
     * The candidate’s prefix id
     * @type {string}
     * @memberof NamePrefix
     */
    'id'?: string;
    /**
     * The candidate’s prefix
     * @type {object}
     * @memberof NamePrefix
     */
    'name'?: object;
}

