/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Organization level
 * @export
 * @interface NewHireReadModelOrganizationLevelsInner
 */
export interface NewHireReadModelOrganizationLevelsInner {
    /**
     * Description of a organization that the new hire is associated with.
     * @type {string}
     * @memberof NewHireReadModelOrganizationLevelsInner
     */
    'description'?: string;
    /**
     * Identifier of the organization level
     * @type {string}
     * @memberof NewHireReadModelOrganizationLevelsInner
     */
    'id'?: string;
    /**
     * Level of the organization level
     * @type {string}
     * @memberof NewHireReadModelOrganizationLevelsInner
     */
    'level'?: NewHireReadModelOrganizationLevelsInnerLevelEnum;
    /**
     * Unique code of a organization that the new hire is associated with
     * @type {string}
     * @memberof NewHireReadModelOrganizationLevelsInner
     */
    'code'?: string;
}

type NewHireReadModelOrganizationLevelsInnerLevelEnum = 'Level 1 = 1' | 'Level 2 = 2' | 'Level 3 = 3' | 'Level 4 = 4'


