/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresGetByIdResponseJobComponentCompany } from './new-hires-get-by-id-response-job-component-company';
import { NewHiresGetByIdResponseJobEmployeeType } from './new-hires-get-by-id-response-job-employee-type';
import { NewHiresGetByIdResponseJobSupervisor } from './new-hires-get-by-id-response-job-supervisor';
import { NewHiresGetByIdResponseJobWorkLocation } from './new-hires-get-by-id-response-job-work-location';

/**
 * Job of the new hire
 * @export
 * @interface NewHiresGetByIdResponseJob
 */
export interface NewHiresGetByIdResponseJob {
    /**
     * Unique identifier of the job
     * @type {string}
     * @memberof NewHiresGetByIdResponseJob
     */
    'id'?: string;
    /**
     * The name of the job
     * @type {{ [key: string]: string; }}
     * @memberof NewHiresGetByIdResponseJob
     */
    'name'?: { [key: string]: string; };
    /**
     * Code of the job
     * @type {string}
     * @memberof NewHiresGetByIdResponseJob
     */
    'code'?: string;
    /**
     * RequisitionId of the job
     * @type {string}
     * @memberof NewHiresGetByIdResponseJob
     */
    'requisitionId'?: string;
    /**
     * Selected FLSA status for the job
     * @type {string}
     * @memberof NewHiresGetByIdResponseJob
     */
    'selectedFLSAStatus'?: NewHiresGetByIdResponseJobSelectedFLSAStatusEnum;
    /**
     * 
     * @type {NewHiresGetByIdResponseJobComponentCompany}
     * @memberof NewHiresGetByIdResponseJob
     */
    'componentCompany'?: NewHiresGetByIdResponseJobComponentCompany;
    /**
     * 
     * @type {NewHiresGetByIdResponseJobWorkLocation}
     * @memberof NewHiresGetByIdResponseJob
     */
    'workLocation'?: NewHiresGetByIdResponseJobWorkLocation;
    /**
     * 
     * @type {NewHiresGetByIdResponseJobSupervisor}
     * @memberof NewHiresGetByIdResponseJob
     */
    'supervisor'?: NewHiresGetByIdResponseJobSupervisor;
    /**
     * 
     * @type {NewHiresGetByIdResponseJobEmployeeType}
     * @memberof NewHiresGetByIdResponseJob
     */
    'employeeType'?: NewHiresGetByIdResponseJobEmployeeType;
}

type NewHiresGetByIdResponseJobSelectedFLSAStatusEnum = 'Not specified = 0' | 'Exempt = 1' | 'NonExempt = 2'


