/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresGetById200ResponseProvisioningProvisioningItemsInnerSelectedOption } from './new-hires-get-by-id200-response-provisioning-provisioning-items-inner-selected-option';

/**
 * An individual provisioning item that is assigned to a new hire
 * @export
 * @interface NewHiresGetById200ResponseProvisioningProvisioningItemsInner
 */
export interface NewHiresGetById200ResponseProvisioningProvisioningItemsInner {
    /**
     * Id of the provisioning item
     * @type {string}
     * @memberof NewHiresGetById200ResponseProvisioningProvisioningItemsInner
     */
    'id'?: string;
    /**
     * Category of the provisioning item
     * @type {string}
     * @memberof NewHiresGetById200ResponseProvisioningProvisioningItemsInner
     */
    'name'?: string;
    /**
     * Recipient of the provisioning item
     * @type {string}
     * @memberof NewHiresGetById200ResponseProvisioningProvisioningItemsInner
     */
    'recipient'?: string;
    /**
     * 
     * @type {NewHiresGetById200ResponseProvisioningProvisioningItemsInnerSelectedOption}
     * @memberof NewHiresGetById200ResponseProvisioningProvisioningItemsInner
     */
    'selectedOption'?: NewHiresGetById200ResponseProvisioningProvisioningItemsInnerSelectedOption;
    /**
     * Comment on the provisioning item
     * @type {string}
     * @memberof NewHiresGetById200ResponseProvisioningProvisioningItemsInner
     */
    'comments'?: string;
}

