/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresGetByIdResponseContactInformationNamePrefix } from './new-hires-get-by-id-response-contact-information-name-prefix';
import { NewHiresGetByIdResponseContactInformationNameSuffix } from './new-hires-get-by-id-response-contact-information-name-suffix';

/**
 * Name of the new hire
 * @export
 * @interface NewHiresGetByIdResponseContactInformationName
 */
export interface NewHiresGetByIdResponseContactInformationName {
    /**
     * 
     * @type {NewHiresGetByIdResponseContactInformationNamePrefix}
     * @memberof NewHiresGetByIdResponseContactInformationName
     */
    'prefix'?: NewHiresGetByIdResponseContactInformationNamePrefix;
    /**
     * First name
     * @type {string}
     * @memberof NewHiresGetByIdResponseContactInformationName
     */
    'first'?: string;
    /**
     * Middle name
     * @type {string}
     * @memberof NewHiresGetByIdResponseContactInformationName
     */
    'middle'?: string;
    /**
     * Last name
     * @type {string}
     * @memberof NewHiresGetByIdResponseContactInformationName
     */
    'last'?: string;
    /**
     * Former last name
     * @type {string}
     * @memberof NewHiresGetByIdResponseContactInformationName
     */
    'formerLast'?: string;
    /**
     * 
     * @type {NewHiresGetByIdResponseContactInformationNameSuffix}
     * @memberof NewHiresGetByIdResponseContactInformationName
     */
    'suffix'?: NewHiresGetByIdResponseContactInformationNameSuffix;
    /**
     * Preferred first name
     * @type {string}
     * @memberof NewHiresGetByIdResponseContactInformationName
     */
    'preferredFirst'?: string;
}

