/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresCreateSingleNewHire201ResponseContactInformationAddress } from './new-hires-create-single-new-hire201-response-contact-information-address';
import { NewHiresCreateSingleNewHire201ResponseContactInformationName } from './new-hires-create-single-new-hire201-response-contact-information-name';

/**
 * Contact information of the new hire
 * @export
 * @interface NewHiresCreateSingleNewHire201ResponseContactInformation
 */
export interface NewHiresCreateSingleNewHire201ResponseContactInformation {
    /**
     * 
     * @type {NewHiresCreateSingleNewHire201ResponseContactInformationName}
     * @memberof NewHiresCreateSingleNewHire201ResponseContactInformation
     */
    'name'?: NewHiresCreateSingleNewHire201ResponseContactInformationName;
    /**
     * Email address of the new hire
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseContactInformation
     */
    'emailAddress'?: string;
    /**
     * Primary phone number of the new hire
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseContactInformation
     */
    'primaryPhone'?: string;
    /**
     * Secondary phone number of the new hire
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseContactInformation
     */
    'secondaryPhone'?: string;
    /**
     * 
     * @type {NewHiresCreateSingleNewHire201ResponseContactInformationAddress}
     * @memberof NewHiresCreateSingleNewHire201ResponseContactInformation
     */
    'address'?: NewHiresCreateSingleNewHire201ResponseContactInformationAddress;
}

