/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresCreateSingleNewHire201ResponseJobSupervisorName } from './new-hires-create-single-new-hire201-response-job-supervisor-name';

/**
 * Supervisor of the job
 * @export
 * @interface NewHiresCreateSingleNewHire201ResponseJobSupervisor
 */
export interface NewHiresCreateSingleNewHire201ResponseJobSupervisor {
    /**
     * Id of the supervisor
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseJobSupervisor
     */
    'id'?: string;
    /**
     * 
     * @type {NewHiresCreateSingleNewHire201ResponseJobSupervisorName}
     * @memberof NewHiresCreateSingleNewHire201ResponseJobSupervisor
     */
    'name'?: NewHiresCreateSingleNewHire201ResponseJobSupervisorName;
    /**
     * The email of the supervisor
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseJobSupervisor
     */
    'email'?: string;
    /**
     * The external user id of the supervisor
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseJobSupervisor
     */
    'externalUserId'?: string;
}

