/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresGetById200ResponseMentorName } from './new-hires-get-by-id200-response-mentor-name';

/**
 * Mentor of the new hire
 * @export
 * @interface NewHiresGetById200ResponseMentor
 */
export interface NewHiresGetById200ResponseMentor {
    /**
     * Description of the mentor
     * @type {string}
     * @memberof NewHiresGetById200ResponseMentor
     */
    'description'?: string;
    /**
     * Id of the mentor
     * @type {string}
     * @memberof NewHiresGetById200ResponseMentor
     */
    'id'?: string;
    /**
     * External user identifier of the mentor
     * @type {string}
     * @memberof NewHiresGetById200ResponseMentor
     */
    'externalUserId'?: string;
    /**
     * Email of the mentor
     * @type {string}
     * @memberof NewHiresGetById200ResponseMentor
     */
    'email'?: string;
    /**
     * 
     * @type {NewHiresGetById200ResponseMentorName}
     * @memberof NewHiresGetById200ResponseMentor
     */
    'name'?: NewHiresGetById200ResponseMentorName;
}

