/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresCreateSingleNewHireResponseJobComponentCompany } from './new-hires-create-single-new-hire-response-job-component-company';
import { NewHiresCreateSingleNewHireResponseJobEmployeeType } from './new-hires-create-single-new-hire-response-job-employee-type';
import { NewHiresCreateSingleNewHireResponseJobSupervisor } from './new-hires-create-single-new-hire-response-job-supervisor';
import { NewHiresCreateSingleNewHireResponseJobWorkLocation } from './new-hires-create-single-new-hire-response-job-work-location';

/**
 * Job of the new hire
 * @export
 * @interface NewHiresCreateSingleNewHireResponseJob
 */
export interface NewHiresCreateSingleNewHireResponseJob {
    /**
     * Unique identifier of the job
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'id'?: string;
    /**
     * The name of the job
     * @type {{ [key: string]: string; }}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'name'?: { [key: string]: string; };
    /**
     * Code of the job
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'code'?: string;
    /**
     * RequisitionId of the job
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'requisitionId'?: string;
    /**
     * Selected FLSA status for the job
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'selectedFLSAStatus'?: NewHiresCreateSingleNewHireResponseJobSelectedFLSAStatusEnum;
    /**
     * 
     * @type {NewHiresCreateSingleNewHireResponseJobComponentCompany}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'componentCompany'?: NewHiresCreateSingleNewHireResponseJobComponentCompany;
    /**
     * 
     * @type {NewHiresCreateSingleNewHireResponseJobWorkLocation}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'workLocation'?: NewHiresCreateSingleNewHireResponseJobWorkLocation;
    /**
     * 
     * @type {NewHiresCreateSingleNewHireResponseJobSupervisor}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'supervisor'?: NewHiresCreateSingleNewHireResponseJobSupervisor;
    /**
     * 
     * @type {NewHiresCreateSingleNewHireResponseJobEmployeeType}
     * @memberof NewHiresCreateSingleNewHireResponseJob
     */
    'employeeType'?: NewHiresCreateSingleNewHireResponseJobEmployeeType;
}

type NewHiresCreateSingleNewHireResponseJobSelectedFLSAStatusEnum = 'Not specified = 0' | 'Exempt = 1' | 'NonExempt = 2'


