/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHireReadModelJobSupervisorName } from './new-hire-read-model-job-supervisor-name';

/**
 * Supervisor of the job
 * @export
 * @interface NewHireReadModelJobSupervisor
 */
export interface NewHireReadModelJobSupervisor {
    /**
     * Id of the supervisor
     * @type {string}
     * @memberof NewHireReadModelJobSupervisor
     */
    'id'?: string;
    /**
     * 
     * @type {NewHireReadModelJobSupervisorName}
     * @memberof NewHireReadModelJobSupervisor
     */
    'name'?: NewHireReadModelJobSupervisorName;
    /**
     * The email of the supervisor
     * @type {string}
     * @memberof NewHireReadModelJobSupervisor
     */
    'email'?: string;
    /**
     * The external user id of the supervisor
     * @type {string}
     * @memberof NewHireReadModelJobSupervisor
     */
    'externalUserId'?: string;
}

