/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresCreateSingleNewHireResponseContactInformationAddressCountry } from './new-hires-create-single-new-hire-response-contact-information-address-country';

/**
 * Address of the new hire
 * @export
 * @interface NewHiresCreateSingleNewHireResponseContactInformationAddress
 */
export interface NewHiresCreateSingleNewHireResponseContactInformationAddress {
    /**
     * Line 1 of the address
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseContactInformationAddress
     */
    'line1'?: string;
    /**
     * Line 2 of the address
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseContactInformationAddress
     */
    'line2'?: string;
    /**
     * City of the address
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseContactInformationAddress
     */
    'city'?: string;
    /**
     * Zip/postal code of the address
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseContactInformationAddress
     */
    'postalCode'?: string;
    /**
     * County of the address
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseContactInformationAddress
     */
    'county'?: string;
    /**
     * State code of the address
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseContactInformationAddress
     */
    'stateCode'?: string;
    /**
     * Country code of the address
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseContactInformationAddress
     */
    'countryCode'?: string;
    /**
     * 
     * @type {NewHiresCreateSingleNewHireResponseContactInformationAddressCountry}
     * @memberof NewHiresCreateSingleNewHireResponseContactInformationAddress
     */
    'country'?: NewHiresCreateSingleNewHireResponseContactInformationAddressCountry;
}

