/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInnerSelectedOption } from './new-hires-create-single-new-hire-response-provisioning-provisioning-items-inner-selected-option';

/**
 * An individual provisioning item that is assigned to a new hire
 * @export
 * @interface NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInner
 */
export interface NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInner {
    /**
     * Id of the provisioning item
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInner
     */
    'id'?: string;
    /**
     * Category of the provisioning item
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInner
     */
    'name'?: string;
    /**
     * Recipient of the provisioning item
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInner
     */
    'recipient'?: string;
    /**
     * 
     * @type {NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInnerSelectedOption}
     * @memberof NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInner
     */
    'selectedOption'?: NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInnerSelectedOption;
    /**
     * Comment on the provisioning item
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireResponseProvisioningProvisioningItemsInner
     */
    'comments'?: string;
}

