/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresGetById404ResponseAllOf1ErrorsGeneral } from './new-hires-get-by-id404-response-all-of1-errors-general';

/**
 * 
 * @export
 * @interface NewHiresGetById404ResponseAllOf1Errors
 */
export interface NewHiresGetById404ResponseAllOf1Errors {
    /**
     * Properties failing validation and the errors associated with each of these properties.
     * @type {object}
     * @memberof NewHiresGetById404ResponseAllOf1Errors
     */
    'modelState'?: object;
    /**
     * 
     * @type {Array<NewHiresGetById404ResponseAllOf1ErrorsGeneral>}
     * @memberof NewHiresGetById404ResponseAllOf1Errors
     */
    'general'?: Array<NewHiresGetById404ResponseAllOf1ErrorsGeneral>;
}

