/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresGetById404ResponseAllOf1Errors } from './new-hires-get-by-id404-response-all-of1-errors';

/**
 * 
 * @export
 * @interface NewHiresGetById404ResponseAllOf1
 */
export interface NewHiresGetById404ResponseAllOf1 {
    /**
     * 
     * @type {NewHiresGetById404ResponseAllOf1Errors}
     * @memberof NewHiresGetById404ResponseAllOf1
     */
    'errors'?: NewHiresGetById404ResponseAllOf1Errors;
}

