/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHireReadModelMentorName } from './new-hire-read-model-mentor-name';

/**
 * Mentor of the new hire
 * @export
 * @interface NewHireReadModelMentor
 */
export interface NewHireReadModelMentor {
    /**
     * Description of the mentor
     * @type {string}
     * @memberof NewHireReadModelMentor
     */
    'description'?: string;
    /**
     * Id of the mentor
     * @type {string}
     * @memberof NewHireReadModelMentor
     */
    'id'?: string;
    /**
     * External user identifier of the mentor
     * @type {string}
     * @memberof NewHireReadModelMentor
     */
    'externalUserId'?: string;
    /**
     * Email of the mentor
     * @type {string}
     * @memberof NewHireReadModelMentor
     */
    'email'?: string;
    /**
     * 
     * @type {NewHireReadModelMentorName}
     * @memberof NewHireReadModelMentor
     */
    'name'?: NewHireReadModelMentorName;
}

