/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresGetByIdResponseOnboardingOwnerName } from './new-hires-get-by-id-response-onboarding-owner-name';

/**
 * Onboarding owner for the new hire
 * @export
 * @interface NewHiresGetByIdResponseOnboardingOwner
 */
export interface NewHiresGetByIdResponseOnboardingOwner {
    /**
     * Id of the onboarding owner
     * @type {string}
     * @memberof NewHiresGetByIdResponseOnboardingOwner
     */
    'id'?: string;
    /**
     * External user identifier of the onboarding owner
     * @type {string}
     * @memberof NewHiresGetByIdResponseOnboardingOwner
     */
    'externalUserId'?: string;
    /**
     * Email of the onboarding owner
     * @type {string}
     * @memberof NewHiresGetByIdResponseOnboardingOwner
     */
    'email'?: string;
    /**
     * 
     * @type {NewHiresGetByIdResponseOnboardingOwnerName}
     * @memberof NewHiresGetByIdResponseOnboardingOwner
     */
    'name'?: NewHiresGetByIdResponseOnboardingOwnerName;
}

