/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresCreateSingleNewHireRequestContactInformationNamePrefix } from './new-hires-create-single-new-hire-request-contact-information-name-prefix';
import { NewHiresCreateSingleNewHireRequestContactInformationNameSuffix } from './new-hires-create-single-new-hire-request-contact-information-name-suffix';

/**
 * Name of the new hire
 * @export
 * @interface NewHiresCreateSingleNewHireRequestContactInformationName
 */
export interface NewHiresCreateSingleNewHireRequestContactInformationName {
    /**
     * 
     * @type {NewHiresCreateSingleNewHireRequestContactInformationNamePrefix}
     * @memberof NewHiresCreateSingleNewHireRequestContactInformationName
     */
    'prefix'?: NewHiresCreateSingleNewHireRequestContactInformationNamePrefix;
    /**
     * First name of the new hire. maxLength: 50 for hires in US/Canadian companies. 100 otherwise
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireRequestContactInformationName
     */
    'first': string;
    /**
     * Middle name of the new hire
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireRequestContactInformationName
     */
    'middle'?: string;
    /**
     * Last name of the new hire. maxLength: 50 for hires in US/Canadian companies. 100 otherwise
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireRequestContactInformationName
     */
    'last': string;
    /**
     * Former last name of the new hire. maxLength: 30 for hires in US/Canadian companies. 100 otherwise
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireRequestContactInformationName
     */
    'formerLast'?: string;
    /**
     * 
     * @type {NewHiresCreateSingleNewHireRequestContactInformationNameSuffix}
     * @memberof NewHiresCreateSingleNewHireRequestContactInformationName
     */
    'suffix'?: NewHiresCreateSingleNewHireRequestContactInformationNameSuffix;
    /**
     * Preferred first name of the new hire. maxLength: 50 for hires in US/Canadian companies. 100 otherwise
     * @type {string}
     * @memberof NewHiresCreateSingleNewHireRequestContactInformationName
     */
    'preferredFirst'?: string;
}

