/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHireReadModelProvisioningProvisioningItemsInnerSelectedOption } from './new-hire-read-model-provisioning-provisioning-items-inner-selected-option';

/**
 * An individual provisioning item that is assigned to a new hire
 * @export
 * @interface NewHireReadModelProvisioningProvisioningItemsInner
 */
export interface NewHireReadModelProvisioningProvisioningItemsInner {
    /**
     * Id of the provisioning item
     * @type {string}
     * @memberof NewHireReadModelProvisioningProvisioningItemsInner
     */
    'id'?: string;
    /**
     * Category of the provisioning item
     * @type {string}
     * @memberof NewHireReadModelProvisioningProvisioningItemsInner
     */
    'name'?: string;
    /**
     * Recipient of the provisioning item
     * @type {string}
     * @memberof NewHireReadModelProvisioningProvisioningItemsInner
     */
    'recipient'?: string;
    /**
     * 
     * @type {NewHireReadModelProvisioningProvisioningItemsInnerSelectedOption}
     * @memberof NewHireReadModelProvisioningProvisioningItemsInner
     */
    'selectedOption'?: NewHireReadModelProvisioningProvisioningItemsInnerSelectedOption;
    /**
     * Comment on the provisioning item
     * @type {string}
     * @memberof NewHireReadModelProvisioningProvisioningItemsInner
     */
    'comments'?: string;
}

