/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Currency of the new hire
 * @export
 * @interface NewHireReadModelCompensationCurrency
 */
export interface NewHireReadModelCompensationCurrency {
    /**
     * Code of the translatable
     * @type {string}
     * @memberof NewHireReadModelCompensationCurrency
     */
    'code'?: string;
    /**
     * The language that the translatable is in
     * @type {{ [key: string]: string; }}
     * @memberof NewHireReadModelCompensationCurrency
     */
    'name'?: { [key: string]: string; };
}

