/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresGetByIdResponseCompensationCurrency } from './new-hires-get-by-id-response-compensation-currency';
import { NewHiresGetByIdResponseCompensationRatePer } from './new-hires-get-by-id-response-compensation-rate-per';

/**
 * Compensation of the new hire
 * @export
 * @interface NewHiresGetByIdResponseCompensation
 */
export interface NewHiresGetByIdResponseCompensation {
    /**
     * Whether the new hire is full time
     * @type {boolean}
     * @memberof NewHiresGetByIdResponseCompensation
     */
    'isFullTime'?: boolean;
    /**
     * Whether the new hire is salaried
     * @type {boolean}
     * @memberof NewHiresGetByIdResponseCompensation
     */
    'isSalaried'?: boolean;
    /**
     * Work hours of the new hire
     * @type {number}
     * @memberof NewHiresGetByIdResponseCompensation
     */
    'workHours'?: number;
    /**
     * Weekly hours of the new hire
     * @type {number}
     * @memberof NewHiresGetByIdResponseCompensation
     */
    'weeklyHours'?: number;
    /**
     * Currency type of the new hire\'s pay
     * @type {string}
     * @memberof NewHiresGetByIdResponseCompensation
     */
    'currencyType'?: string;
    /**
     * 
     * @type {NewHiresGetByIdResponseCompensationCurrency}
     * @memberof NewHiresGetByIdResponseCompensation
     */
    'currency'?: NewHiresGetByIdResponseCompensationCurrency;
    /**
     * Pay rate of the new hire
     * @type {number}
     * @memberof NewHiresGetByIdResponseCompensation
     */
    'payRate'?: number;
    /**
     * 
     * @type {NewHiresGetByIdResponseCompensationRatePer}
     * @memberof NewHiresGetByIdResponseCompensation
     */
    'ratePer'?: NewHiresGetByIdResponseCompensationRatePer;
}

