/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHireReadModelJobSupervisorNamePrefix } from './new-hire-read-model-job-supervisor-name-prefix';
import { NewHireReadModelJobSupervisorNameSuffix } from './new-hire-read-model-job-supervisor-name-suffix';

/**
 * Name of the supervisor
 * @export
 * @interface NewHireReadModelJobSupervisorName
 */
export interface NewHireReadModelJobSupervisorName {
    /**
     * 
     * @type {NewHireReadModelJobSupervisorNamePrefix}
     * @memberof NewHireReadModelJobSupervisorName
     */
    'prefix'?: NewHireReadModelJobSupervisorNamePrefix;
    /**
     * First name
     * @type {string}
     * @memberof NewHireReadModelJobSupervisorName
     */
    'first'?: string;
    /**
     * Middle name
     * @type {string}
     * @memberof NewHireReadModelJobSupervisorName
     */
    'middle'?: string;
    /**
     * Last name
     * @type {string}
     * @memberof NewHireReadModelJobSupervisorName
     */
    'last'?: string;
    /**
     * Former last name
     * @type {string}
     * @memberof NewHireReadModelJobSupervisorName
     */
    'formerLast'?: string;
    /**
     * 
     * @type {NewHireReadModelJobSupervisorNameSuffix}
     * @memberof NewHireReadModelJobSupervisorName
     */
    'suffix'?: NewHireReadModelJobSupervisorNameSuffix;
    /**
     * Preferred first name
     * @type {string}
     * @memberof NewHireReadModelJobSupervisorName
     */
    'preferredFirst'?: string;
}

