/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHireReadModelContactInformationAddressCountry } from './new-hire-read-model-contact-information-address-country';

/**
 * Address of the new hire
 * @export
 * @interface NewHireReadModelContactInformationAddress
 */
export interface NewHireReadModelContactInformationAddress {
    /**
     * Line 1 of the address
     * @type {string}
     * @memberof NewHireReadModelContactInformationAddress
     */
    'line1'?: string;
    /**
     * Line 2 of the address
     * @type {string}
     * @memberof NewHireReadModelContactInformationAddress
     */
    'line2'?: string;
    /**
     * City of the address
     * @type {string}
     * @memberof NewHireReadModelContactInformationAddress
     */
    'city'?: string;
    /**
     * Zip/postal code of the address
     * @type {string}
     * @memberof NewHireReadModelContactInformationAddress
     */
    'postalCode'?: string;
    /**
     * County of the address
     * @type {string}
     * @memberof NewHireReadModelContactInformationAddress
     */
    'county'?: string;
    /**
     * State code of the address
     * @type {string}
     * @memberof NewHireReadModelContactInformationAddress
     */
    'stateCode'?: string;
    /**
     * Country code of the address
     * @type {string}
     * @memberof NewHireReadModelContactInformationAddress
     */
    'countryCode'?: string;
    /**
     * 
     * @type {NewHireReadModelContactInformationAddressCountry}
     * @memberof NewHireReadModelContactInformationAddress
     */
    'country'?: NewHireReadModelContactInformationAddressCountry;
}

