/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { NewHiresCreateSingleNewHire201ResponseMentorName } from './new-hires-create-single-new-hire201-response-mentor-name';

/**
 * Mentor of the new hire
 * @export
 * @interface NewHiresCreateSingleNewHire201ResponseMentor
 */
export interface NewHiresCreateSingleNewHire201ResponseMentor {
    /**
     * Description of the mentor
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseMentor
     */
    'description'?: string;
    /**
     * Id of the mentor
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseMentor
     */
    'id'?: string;
    /**
     * External user identifier of the mentor
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseMentor
     */
    'externalUserId'?: string;
    /**
     * Email of the mentor
     * @type {string}
     * @memberof NewHiresCreateSingleNewHire201ResponseMentor
     */
    'email'?: string;
    /**
     * 
     * @type {NewHiresCreateSingleNewHire201ResponseMentorName}
     * @memberof NewHiresCreateSingleNewHire201ResponseMentor
     */
    'name'?: NewHiresCreateSingleNewHire201ResponseMentorName;
}

