/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Work location of the job
 * @export
 * @interface NewHireReadModelJobWorkLocation
 */
export interface NewHireReadModelJobWorkLocation {
    /**
     * Id of the work location
     * @type {string}
     * @memberof NewHireReadModelJobWorkLocation
     */
    'id'?: string;
    /**
     * Name of the work location
     * @type {string}
     * @memberof NewHireReadModelJobWorkLocation
     */
    'name'?: string;
}

