/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Prefix of the new hire in translatable format
 * @export
 * @interface NewHiresGetById200ResponseContactInformationNamePrefix
 */
export interface NewHiresGetById200ResponseContactInformationNamePrefix {
    /**
     * Id of the translatable
     * @type {string}
     * @memberof NewHiresGetById200ResponseContactInformationNamePrefix
     */
    'id'?: string;
    /**
     * The language that the translatable is in
     * @type {{ [key: string]: string; }}
     * @memberof NewHiresGetById200ResponseContactInformationNamePrefix
     */
    'name'?: { [key: string]: string; };
}

