/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OpenEnrollmentDependentDeductions
 */
export interface OpenEnrollmentDependentDeductions {
    /**
     * 
     * @type {number}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'benefitAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'changeReason'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'relationship'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'benefitStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'benefitStatus'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'benefitStatusDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'benefitStopDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'companyId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'changeDatetime'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'contactId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'createDatetime'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'certificateNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'currentCoId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'declinedByCarrier'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'declinedByCarrierDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'declinedByCarrierReason'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'deductionCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'deductionType'?: string;
    /**
     * 
     * @type {number}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'depBPlanTVID'?: number;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'employeeId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'evidenceofInsurabilityDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'needEvidenceOfInsurability'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'employerAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'deductionNotes'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'primaryCarePhysician'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'primaryCarePhysicianId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'systemId'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'isBenefitWaived'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OpenEnrollmentDependentDeductions
     */
    'oeDrop'?: boolean;
}

