/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EducationCriteria } from './education-criteria';
import { JobBoards } from './job-boards';
import { Links } from './links';
import { Locations } from './locations';
import { OpportunityCompany } from './opportunity-company';
import { OpportunityCompenasation } from './opportunity-compenasation';
import { OpportunityCompenasationCurrency } from './opportunity-compenasation-currency';
import { OpportunityDedaultLocale } from './opportunity-dedault-locale';
import { OpportunityDescription } from './opportunity-description';
import { OpportunityFullTimeEquivalent } from './opportunity-full-time-equivalent';
import { OpportunityHeadCount } from './opportunity-head-count';
import { OpportunityIncumbent } from './opportunity-incumbent';
import { OpportunityJobFamily } from './opportunity-job-family';
import { OpportunityRecruitingProcess } from './opportunity-recruiting-process';
import { OrgUnitGroups } from './org-unit-groups';

/**
 * The section that contains details of an opportunity associated with the candidate’s application
 * @export
 * @interface Opportunity
 */
export interface Opportunity {
    /**
     * 
     * @type {object}
     * @memberof Opportunity
     */
    'title'?: object;
    /**
     * 
     * @type {OpportunityDescription}
     * @memberof Opportunity
     */
    'description'?: OpportunityDescription;
    /**
     * The id of the opportunity associated with the candidate application.
     * @type {string}
     * @memberof Opportunity
     */
    'id'?: string;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'updated_at'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'created_at'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'requisition_number'?: any;
    /**
     * 
     * @type {OpportunityDedaultLocale}
     * @memberof Opportunity
     */
    'dedault_locale'?: OpportunityDedaultLocale;
    /**
     * 
     * @type {OpportunityCompenasation}
     * @memberof Opportunity
     */
    'compenasation'?: OpportunityCompenasation;
    /**
     * 
     * @type {OpportunityCompenasationCurrency}
     * @memberof Opportunity
     */
    'job'?: OpportunityCompenasationCurrency;
    /**
     * 
     * @type {OpportunityJobFamily}
     * @memberof Opportunity
     */
    'job_family'?: OpportunityJobFamily;
    /**
     * 
     * @type {Array<Locations>}
     * @memberof Opportunity
     */
    'locations'?: Array<Locations>;
    /**
     * 
     * @type {OpportunityCompany}
     * @memberof Opportunity
     */
    'company'?: OpportunityCompany;
    /**
     * 
     * @type {object}
     * @memberof Opportunity
     */
    'recruiter'?: object;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'hiring_manager'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'onboarding_owner'?: any;
    /**
     * 
     * @type {OpportunityRecruitingProcess}
     * @memberof Opportunity
     */
    'recruiting_process'?: OpportunityRecruitingProcess;
    /**
     * 
     * @type {Array<JobBoards>}
     * @memberof Opportunity
     */
    'job_boards'?: Array<JobBoards>;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'published_date'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'closed_date'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'status'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'is_featured'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'is_shared_with_everyone'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'internal_notes'?: any;
    /**
     * 
     * @type {Array<any>}
     * @memberof Opportunity
     */
    'skill_criteria'?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof Opportunity
     */
    'work_experience_criteria'?: Array<any>;
    /**
     * 
     * @type {Array<EducationCriteria>}
     * @memberof Opportunity
     */
    'education_criteria'?: Array<EducationCriteria>;
    /**
     * 
     * @type {Array<any>}
     * @memberof Opportunity
     */
    'license_criteria'?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof Opportunity
     */
    'behavior_criteria'?: Array<any>;
    /**
     * 
     * @type {Array<any>}
     * @memberof Opportunity
     */
    'motivation_criteria'?: Array<any>;
    /**
     * 
     * @type {boolean}
     * @memberof Opportunity
     */
    'is_continuous_opening'?: boolean;
    /**
     * 
     * @type {OpportunityFullTimeEquivalent}
     * @memberof Opportunity
     */
    'full_time_equivalent'?: OpportunityFullTimeEquivalent;
    /**
     * 
     * @type {OpportunityHeadCount}
     * @memberof Opportunity
     */
    'head_count'?: OpportunityHeadCount;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'hours_per_week'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'hours_per_shift'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'staffing_plan_impact'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'target_start_date'?: any;
    /**
     * 
     * @type {OpportunityIncumbent}
     * @memberof Opportunity
     */
    'incumbent'?: OpportunityIncumbent;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'priority'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'is_budgeted'?: any;
    /**
     * 
     * @type {any}
     * @memberof Opportunity
     */
    'opening_reason'?: any;
    /**
     * 
     * @type {Array<any>}
     * @memberof Opportunity
     */
    'justification_comments'?: Array<any>;
    /**
     * 
     * @type {Array<OrgUnitGroups>}
     * @memberof Opportunity
     */
    'org_unit_groups'?: Array<OrgUnitGroups>;
    /**
     * 
     * @type {Array<Links>}
     * @memberof Opportunity
     */
    'links'?: Array<Links>;
}

