/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OpportunityHeadCount
 */
export interface OpportunityHeadCount {
    /**
     * 
     * @type {any}
     * @memberof OpportunityHeadCount
     */
    'max'?: any;
    /**
     * 
     * @type {any}
     * @memberof OpportunityHeadCount
     */
    'hired'?: any;
    /**
     * 
     * @type {any}
     * @memberof OpportunityHeadCount
     */
    'remaining'?: any;
}

