/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrgUnits } from './org-units';

/**
 * 
 * @export
 * @interface OrgUnitGroups
 */
export interface OrgUnitGroups {
    /**
     * 
     * @type {Array<OrgUnits>}
     * @memberof OrgUnitGroups
     */
    'org_units'?: Array<OrgUnits>;
}

