/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OrgLevelsBodyInner
 */
export interface OrgLevelsBodyInner {
    /**
     * Organization Level Description.
     * @type {string}
     * @memberof OrgLevelsBodyInner
     */
    'description': string;
    /**
     * Organizational budget group.
     * @type {string}
     * @memberof OrgLevelsBodyInner
     */
    'budgetGroup'?: string;
    /**
     * Organization Code, one half of the unique identifier.
     * @type {string}
     * @memberof OrgLevelsBodyInner
     */
    'code': string;
    /**
     * Current year to date budget for full time employee.
     * @type {number}
     * @memberof OrgLevelsBodyInner
     */
    'currentYearBudgetFTE'?: number;
    /**
     * Current year to date budget for salary.
     * @type {number}
     * @memberof OrgLevelsBodyInner
     */
    'currentYearBudgetSalary'?: number;
    /**
     * General Ledger Segment. Alpha-numeric and special characters allowed.
     * @type {string}
     * @memberof OrgLevelsBodyInner
     */
    'glSegment'?: string;
    /**
     * Last year Budget for full time employee.
     * @type {number}
     * @memberof OrgLevelsBodyInner
     */
    'lastYearBudgetFTE'?: number;
    /**
     * Last year Budget salary.
     * @type {number}
     * @memberof OrgLevelsBodyInner
     */
    'lastYearBudgetSalary'?: number;
    /**
     * Organazation Level, one half of unique identifier. Cannot be updated.
     * @type {number}
     * @memberof OrgLevelsBodyInner
     */
    'level': number;
    /**
     * Organization description. Cannot be updated.
     * @type {string}
     * @memberof OrgLevelsBodyInner
     */
    'levelDescription'?: string;
    /**
     * The reporting category code.
     * @type {string}
     * @memberof OrgLevelsBodyInner
     */
    'reportingCategory'?: string;
    /**
     * The organization level status.
     * @type {boolean}
     * @memberof OrgLevelsBodyInner
     */
    'isActive'?: boolean;
}

