/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PayGroupPayPeriods
 */
export interface PayGroupPayPeriods {
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'dateTimeChanged'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'dateTimeCreated'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'dateTimeFiscalEndDone'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'dateTimePeriodClosed'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'dateTimePeriodOpened'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'fiscalYearEnd'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'isCtsCreated'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'isPeriodClosed'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'isQtdobPerControl'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'isYtdobPerControl'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PayGroupPayPeriods
     */
    'monthlyPayPeriodNumber'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'mqyEndFlag'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'obType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'payDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayGroupPayPeriods
     */
    'payDateSeq'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'payGroup'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayGroupPayPeriods
     */
    'payPeriodId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'periodControl'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'periodEndDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'periodStartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'periodType'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'suspAutoPay'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'suspDirectDeposit'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'userIdChanged'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'userIdCreated'?: string;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'notes'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayGroupPayPeriods
     */
    'auditKey'?: number;
    /**
     * 
     * @type {number}
     * @memberof PayGroupPayPeriods
     */
    'payrollStateId'?: number;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'combineNachaFileName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'combineNachaFileOverride'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'txFilAppDateTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof PayGroupPayPeriods
     */
    'txFilAppUserId'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'allowWebPyrlAfterYeRecon'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PayGroupPayPeriods
     */
    'payrollChangeFlags'?: number;
    /**
     * 
     * @type {number}
     * @memberof PayGroupPayPeriods
     */
    'payrollTransitionFlags'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'instantCheckMoveRule'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'bringInPayrollBatchLoad'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'bringInPpiLoad'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'bringInRetroPayLoad'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'lmwActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PayGroupPayPeriods
     */
    'roePayDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PayGroupPayPeriods
     */
    'taxArrearsCollectEnabled'?: boolean;
}

