/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PostingsInnerLocalesInner
 */
export interface PostingsInnerLocalesInner {
    /**
     * Locale identifier, one of the following codes: en-US, en-GB, es-ES, fr-CA, de-DE, or pr-BR. 
     * @type {string}
     * @memberof PostingsInnerLocalesInner
     */
    'code'?: string;
}

