/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PtoPlans
 */
export interface PtoPlans {
    /**
     * Employee Identifier
     * @type {string}
     * @memberof PtoPlans
     */
    'employeeId': string;
    /**
     * Company Identifier
     * @type {string}
     * @memberof PtoPlans
     */
    'companyId': string;
    /**
     * PTO Plan Identifier
     * @type {string}
     * @memberof PtoPlans
     */
    'ptoPlan': string;
    /**
     * Amount of hours earned for PTO
     * @type {number}
     * @memberof PtoPlans
     */
    'earned'?: number;
    /**
     * Amount of hours taken for PTO
     * @type {number}
     * @memberof PtoPlans
     */
    'taken'?: number;
    /**
     * Balance of PTO hours
     * @type {number}
     * @memberof PtoPlans
     */
    'pendingBalance'?: number;
    /**
     * Date in which PTO is earned through, format should be YYYY-MM-DD
     * @type {string}
     * @memberof PtoPlans
     */
    'earnedThroughDate'?: string;
    /**
     * Date in which the PTO reset\'s, format should be YYYY-MM-DD
     * @type {string}
     * @memberof PtoPlans
     */
    'reset'?: string;
    /**
     * Date to be used if pending rules are relevant, format should be YYYY-MM-DD
     * @type {string}
     * @memberof PtoPlans
     */
    'pendingMoveDate'?: string;
}

