/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Roles
 */
export interface Roles {
    /**
     * 
     * @type {boolean}
     * @memberof Roles
     */
    'rolDefaultRole'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Roles
     */
    'rolDescription'?: string;
    /**
     * 
     * @type {number}
     * @memberof Roles
     */
    'rolID'?: number;
    /**
     * 
     * @type {string}
     * @memberof Roles
     */
    'rolName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Roles
     */
    'rolDefaultRoleTerminated'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Roles
     */
    'rolBI'?: boolean;
}

