/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ScreeningQuestionResponsesQuestions } from './screening-question-responses-questions';

/**
 * 
 * @export
 * @interface ScreeningQuestionResponses
 */
export interface ScreeningQuestionResponses {
    /**
     * 
     * @type {ScreeningQuestionResponsesQuestions}
     * @memberof ScreeningQuestionResponses
     */
    'questions'?: ScreeningQuestionResponsesQuestions;
}

