/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The name of the skill in all available languages.
 * @export
 * @interface SkillSkillName
 */
export interface SkillSkillName {
    /**
     * 
     * @type {any}
     * @memberof SkillSkillName
     */
    'en_us'?: any;
}

