/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TimeOffTypeDto
 */
export interface TimeOffTypeDto {
    /**
     * 
     * @type {number}
     * @memberof TimeOffTypeDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeOffTypeDto
     */
    'locName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeOffTypeDto
     */
    'locDesc'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeOffTypeDto
     */
    'name'?: string;
}

