/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * This is an encrypted string, JWT token
     * @type {string}
     * @memberof TokenResponse
     */
    'access_token'?: string;
    /**
     * Bearer token
     * @type {string}
     * @memberof TokenResponse
     */
    'token_type'?: string;
    /**
     * When the token will expire, in seconds
     * @type {number}
     * @memberof TokenResponse
     */
    'expires_in'?: number;
    /**
     * the scope of what you are entitled to access, part of your integration setup
     * @type {string}
     * @memberof TokenResponse
     */
    'scope'?: string;
}

