/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsFieldData } from './ultimate-software-foundation-services-api-ulti-pro-personnel-platform-configuration-v2-models-field-data';

/**
 * 
 * @export
 * @interface UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsPcData
 */
export interface UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsPcData {
    /**
     * 
     * @type {Array<UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsFieldData>}
     * @memberof UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsPcData
     */
    'fieldRows'?: Array<UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsFieldData>;
    /**
     * 
     * @type {string}
     * @memberof UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsPcData
     */
    'className'?: string;
    /**
     * 
     * @type {string}
     * @memberof UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsPcData
     */
    'keyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UltimateSoftwareFoundationServicesApiUltiProPersonnelPlatformConfigurationV2ModelsPcData
     */
    'keyValue'?: string;
}

