/*
User Profile Details

Configure your UKG Pro Configuration Codes through UKG Pro APIs. Status: R1 deployment

The version of the OpenAPI document: v1


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CalcGroupDto } from './calc-group-dto';
import { PayGroupDto } from './pay-group-dto';
import { WorkDetailDto } from './work-detail-dto';
import { WorkSummaryClocksDto } from './work-summary-clocks-dto';

/**
 * 
 * @export
 * @interface WorkSummaryDto
 */
export interface WorkSummaryDto {
    /**
     * 
     * @type {number}
     * @memberof WorkSummaryDto
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkSummaryDto
     */
    'empId'?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'workDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkSummaryDto
     */
    'wrkMins'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof WorkSummaryDto
     */
    'authorized'?: boolean;
    /**
     * true if work summary contain details with an overtime hour type
     * @type {boolean}
     * @memberof WorkSummaryDto
     */
    'overtime'?: boolean;
    /**
     * true if LTA override exists on day
     * @type {boolean}
     * @memberof WorkSummaryDto
     */
    'absent'?: boolean;
    /**
     * time code used in LTA override if present
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'absentTimeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'authorizedMessage'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'comments'?: string;
    /**
     * 
     * @type {WorkSummaryClocksDto}
     * @memberof WorkSummaryDto
     */
    'clocks'?: WorkSummaryClocksDto;
    /**
     * 
     * @type {Array<WorkDetailDto>}
     * @memberof WorkSummaryDto
     */
    'workDetails'?: Array<WorkDetailDto>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkSummaryDto
     */
    'exceptions'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'wrksMessages'?: string;
    /**
     * true if timesheet has been locked
     * @type {boolean}
     * @memberof WorkSummaryDto
     */
    'readOnly'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'readOnlyReason'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WorkSummaryDto
     */
    'daily'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'flag1'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'flag2'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'flag3'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'flag4'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'flag5'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf1'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf2'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf3'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf4'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf5'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf6'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf7'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf8'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf9'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkSummaryDto
     */
    'udf10'?: string;
    /**
     * 
     * @type {PayGroupDto}
     * @memberof WorkSummaryDto
     */
    'payGroup'?: PayGroupDto;
    /**
     * 
     * @type {CalcGroupDto}
     * @memberof WorkSummaryDto
     */
    'calcGroup'?: CalcGroupDto;
}

